apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-gitlab
  namespace: argocd
spec:
  project: default
  
  source:
    # GitLab repository URL (update with your actual GitLab project)
    # Format: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/<project-name>.git
    repoURL: 'http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot-app.git'
    targetRevision: HEAD
    path: .
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
