apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-bonus
servers: 1
agents: 1

kubeAPI:
  host: "0.0.0.0"
  hostPort: "6443"

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

# Optional: volume for persistence (GitLab PVs will still use the cluster's default StorageClass)
# volumes:
#   - volume: /var/lib/k3d-storage:/var/lib/rancher/k3s/storage
#     nodeFilters:
#       - all
