apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alrahmou-dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/usrali2026/Inception_of_Things.git"
    targetRevision: HEAD
    path: "p3/k8s/dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
