apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-app
  namespace: argocd
spec:
  project: default

  source:
    # CHANGE THIS to your actual GitLab project URL
    repoURL: http://gitlab.local/root/app-config.git
    targetRevision: main
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
