# p2/Vagrantfile
# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2404"

  config.vm.define "alrahmouS" do |vm|
    vm.vm.hostname = "alrahmouS"
    vm.vm.network "private_network", ip: "192.168.56.110"

    # Sync configuration folder
    vm.vm.synced_folder "./confs", "/vagrant/confs", type: "rsync", rsync__auto: true

    # ---------- VirtualBox Provider ----------
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = 2048   # drop to 1024 if needed
      vb.cpus   = 1
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    # ---------- Basic tools ----------
    vm.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y curl
    SHELL

    # ---------- Install K3s + apps + ingress ----------
    vm.vm.provision "shell", path: "scripts/install_k3s_and_apps.sh"
  end
end
