Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "alrahmouS"
  config.vm.network "private_network", ip: "10.0.56.110",
    libvirt__network_name: "iot-net",
    libvirt__dhcp_enabled: false,
    libvirt__forward_mode: "none"
  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [".git/"]
  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus   = 2
  end
  config.vm.provision "shell", path: "scripts/install.sh"
  config.vm.provision "shell", path: "scripts/deploy.sh"
end
