# p1/Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box         = "generic/ubuntu2204"
  config.vm.box_version = ">= 4.3.12"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

  config.vm.provider :libvirt do |lv|
    lv.uri               = ENV.fetch("LIBVIRT_DEFAULT_URI", "qemu:///system")
    lv.cpus              = 1
    lv.memory            = 1024
    lv.storage_pool_name = ENV.fetch("VAGRANT_LIBVIRT_STORAGE_POOL", "default")
    lv.disk_bus          = "virtio"
    lv.video_type        = "virtio"
    lv.graphics_type     = "spice"
  end

  # ---------- alrahmouS (server) ----------
  config.vm.define "alrahmouS" do |m|
    m.vm.hostname = "alrahmouS"
    m.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name:    "vagrant-56",
      libvirt__netmask:         "255.255.255.0",
      libvirt__network_address: "192.168.56.0",
      libvirt__dhcp_enabled:    true,
      libvirt__dhcp_start:      "192.168.56.50",
      libvirt__dhcp_stop:       "192.168.56.99"

    m.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # ---------- alrahmouSW (worker) ----------
  config.vm.define "alrahmouSW" do |m|
    m.vm.hostname = "alrahmouSW"
    m.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name:    "vagrant-56",
      libvirt__netmask:         "255.255.255.0",
      libvirt__network_address: "192.168.56.0",
      libvirt__dhcp_enabled:    true,
      libvirt__dhcp_start:      "192.168.56.50",
      libvirt__dhcp_stop:       "192.168.56.99"

    m.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
